    [unifiedDerivedTimes, timeDomainData, timeDomainData_onlyTimeVariables,...
        timeDomain_timeVariableNames, AccelData, AccelData_onlyTimeVariables,...
        Accel_timeVariableNames, PowerData, PowerData_onlyTimeVariables,...
        Power_timeVariableNames, FFTData, FFTData_onlyTimeVariables,...
        FFT_timeVariableNames, AdaptiveData, AdaptiveData_onlyTimeVariables, ...
        Adaptive_timeVariableNames, timeDomainSettings, powerSettings, fftSettings, ...
        eventLogTable, metaData, stimSettingsOut, stimMetaData, stimLogSettings,...
        DetectorSettings, AdaptiveStimSettings, AdaptiveEmbeddedRuns_StimSettings] = ProcessRCS();
